# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67179e0b8fce1ac7d70246f078c3ebe670557b0d8a1f92ce9781a749f085a2bd436826659b9803a141af974664f70f38a7b32b1a95b10d51542a8e9b1fee239a

test:
  secret_key_base: de38281770bbf0e88619c1e6fdd2ac178006b9e1f0bdd2555c94f51f31ab5298a43ad1a2a695df84ebc79ce9ab583dad90968105f8773f4ca45ad275a6c03697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
